"""
Copyright (c) 2023-2024 Intel Corporation
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
"""

TRUSTAUTHORITY_BASE_URL = "ENV_TRUSTAUTHORITY_BASE_URL"
TRUSTAUTHORITY_API_URL = "ENV_TRUSTAUTHORITY_API_URL"
TRUSTAUTHORITY_API_KEY = "ENV_TRUSTAUTHORITY_API_KEY"
TRUSTAUTHORITY_REQUEST_ID = "ENV_TRUSTAUTHORITY_REQUEST_ID"
TRUSTAUTHORITY_POLICY_ID = "ENV_TRUSTAUTHORITY_POLICY_ID"
RETRY_MAX = "ENV_RETRY_MAX"
RETRY_WAIT_TIME = "RETRY_WAIT_TIME"
DEFAULT_RETRY_MAX = 2
DEFAULT_RETRY_WAIT_TIME = 2
HTTP_PROXY = "http://proxy-us.intel.com:911"
HTTPS_PROXY = "http://proxy-us.intel.com:911"
