"""
Copyright (c) 2023-2024 Intel Corporation
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
"""

TRUSTAUTHORITY_BASE_URL = "ENV_TRUSTAUTHORITY_BASE_URL"
TRUSTAUTHORITY_API_URL = "ENV_TRUSTAUTHORITY_API_URL"
TRUSTAUTHORITY_API_KEY = "ENV_TRUSTAUTHORITY_API_KEY"
TRUSTAUTHORITY_REQUEST_ID = "ENV_TRUSTAUTHORITY_REQUEST_ID"
TRUSTAUTHORITY_POLICY_ID = "ENV_TRUSTAUTHORITY_POLICY_ID"
RETRY_MAX = "ENV_RETRY_MAX"
RETRY_WAIT_TIME_MAX_SEC = "ENV_RETRY_WAIT_TIME_MAX"
RETRY_WAIT_TIME_MIN_SEC = "ENV_RETRY_WAIT_TIME_MIN"
DEFAULT_RETRY_WAIT_MIN_SEC = 2
DEFAULT_RETRY_WAIT_MAX_SEC = 2
DEFAULT_RETRY_MAX_NUM = 2
ATS_CERTCHAIN_MAXLENGTH = 10
HTTP_PROXY = "ENV_HTTP_PROXY"
HTTPS_PROXY = "ENV_HTTPS_PROXY"
ADAPTER_TYPE = "ENV_ADAPTER_TYPE"
