[tool.poetry]
name = "applications-security-amber-trustauthority-client-for-python"
version = "0.1.0"
description = "Amber Client in Python"
authors = ["Kamal, Shefali <shefali.kamal@intel.com>"]
license = "Copyright (c) 2024 Intel Corporation. All rights reserved."
readme = "README.md"
packages = [{include = "applications"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
