[tool.poetry]
name = "applications.security.amber.trustauthority-client-for-python"
version = "1.0.0"
description = "Intel Trust Authority Client in Python"
authors = ["Kamal, Shefali <shefali.kamal@intel.com>", "Bala, K Manisai <k.manisai.bala@intel.com>"]
license = "Copyright (c) 2024 Intel Corporation. All rights reserved."
readme = "README.md"
packages = [{include = "inteltrustauthorityclient"}]
exclude = ["inteltrustauthorityclient/examples"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
validators = "^0.22.0"
resources = "^0.0.1"
staty = "^1.2.4"
cryptography = "^42.0.2"
pyjwt = "^2.8.0"
tenacity = "^8.2.3"
coverage = "^7.4.2"
pytest = "^8.0.2"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
