[tool.poetry]
name = "applications-security-amber-trustauthority-client-for-python"
version = "0.1.0"
description = "Intel Trust Authority Client in Python"
authors = ["Kamal, Shefali <shefali.kamal@intel.com>"]
license = "Copyright (c) 2024 Intel Corporation. All rights reserved."
readme = "README.md"
exclude = [
                { path = "examples" }
          ]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
validators = "^0.22.0"
jwt = "^1.3.1"
resources = "^0.0.1"
staty = "^1.2.4"

[tool.poetry.group.dev.dependencies]
black = "^24.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"