"""
Copyright (c) 2023-2024 Intel Corporation
All rights reserved.
SPDX-License-Identifier: BSD-3-Clause
"""

DEFAULT_RETRY_WAIT_MIN_SEC = 2
DEFAULT_RETRY_WAIT_MAX_SEC = 2
DEFAULT_RETRY_MAX_NUM = 2
DEFAULT_CLIENT_TIMEOUT_SEC = 30
ATS_CERTCHAIN_MAXLENGTH = 10
REQUEST_ID_MAX_LEN = 128
POLICY_IDS_MAX_LEN = 10
HTTP_PROXY = "HTTP_PROXY"
HTTPS_PROXY = "HTTPS_PROXY"
HTTP_HEADER_API_KEY = "x-api-key"
HTTP_HEADER_APPLICATION_JSON = "application/json"
NV_GPU_ADAPTER = "NV-GPU"
HTTP_HEADER_KEY_ACCEPT = "Accept"
HTTP_HEADER_KEY_CONTENT_TYPE = "Content-Type"
HTTP_HEADER_REQUEST_ID = "Request-Id"


# Intel Trust Authority URLs
NONCE_URL = "appraisal/v2/nonce"
AZURE_TDX_ATTEST_URL = "appraisal/v1/attest/azure/tdxvm"
INTEL_TDX_ATTEST_URL = "appraisal/v1/attest"
COMPOSITE_ATTEST_URL = "appraisal/v2/attest"

# GCP Specific
TDX_ATTEST_DEV_PATH = "/dev/tdx_guest"
REQ_BUF_SIZE = 4 * 4 * 1024
TDX_REPORT_OFFSET = 32
TDX_REPORT_DATA_LEN = 64
TDX_REPORT_SIZE = 1024
RUNTIME_DATA_SIZE_OFFSET = 1232
RUNTIME_DATA_OFFSET = 1236
IOC_WRITE = 1
IOC_READ = 2
IOC_NR_BITS = 8
IOC_TYPE_BITS = 8
IOC_SIZE_BITS = 14
IOC_NR_SHIFT = 0
IOC_TYPE_SHIFT = IOC_NR_SHIFT + IOC_NR_BITS
IOC_SIZE_SHIFT = IOC_TYPE_SHIFT + IOC_TYPE_BITS
IOC_DIR_SHIFT = IOC_SIZE_SHIFT + IOC_SIZE_BITS

# SGX Specific
SGX_REPORT_BODY_RESERVED1_BYTES = 12
SGX_REPORT_BODY_RESERVED2_BYTES = 32
SGX_REPORT_BODY_RESERVED3_BYTES = 32
SGX_REPORT_BODY_RESERVED4_BYTES = 42
SGX_TARGET_INFO_RESERVED1_BYTES = 2
SGX_TARGET_INFO_RESERVED2_BYTES = 8
SGX_TARGET_INFO_RESERVED3_BYTES = 384
