###########################################
# Copyright (c) 2023-2024 Intel Corporation
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
###########################################

version: '3'
services:
  trust_authority_python_client_sgx_sample_app:
    image: trust_authority_python_client_sgx_sample_app:${TRUST_AUTHORITY_CLIENT_VERSION}
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    container_name: trust_authority_python_client_sgx_sample_app
    read_only: true
    build:
      context: ../../..
      dockerfile: inteltrustauthorityclient/examples/sgx_sample_app/Dockerfile
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - DCAP_VERSION=${DCAP_VERSION}
        - PSW_VERSION=${PSW_VERSION}
        - ADAPTER_TYPE=${ADAPTER_TYPE}
    env_file:
      - ../.env
