name: OnMergeRelease

on:
  push:
    branches:
      - 'main'
      - 'release/*'
    tags:
      - '**'

jobs:
  build-test-scan:
    runs-on: [ ubuntu-20.04 ]
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Install dependencies via Poetry
        run:  poetry install

      - name: Run UT with Coverage enabled
        run: poetry run coverage run -m unittest discover -s test -p 'test_*.py'
      
      - name: Check coverage percentage
        run: |
            coverage_percentage=$(coverage report --format=total)
            if [ $coverage_percentage -lt 80 ]; then
              echo "Coverage is less than 80%: $coverage_percentage %"
              exit 1
            else
              echo "Coverage is greater than 80 : $coverage_percentage %"
            fi
