name: OnPullRequest

on:
  pull_request:

jobs:
  build-test-scan:
    runs-on: [ ubuntu-20.04 ]
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: python linter TODO: Check if innersource provides aby linter.
       # uses: psf/black@stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Install dependencies via Poetry
        run:  poetry install

      - name: Install Coverage
        run: pip install coverage

      - name: Run UT with Coverage enabled
        working-directory: ./test
        run: |
            export PYTHONPATH=$PYTHONPATH:..
            coverage run -m unittest test_connector.py
            coverage run -a -m unittest test_config.py
            coverage run -a -m unittest test_tdx_adapter.py
      
      - name: Check coverage percentage
        working-directory: ./test
        run: |
            coverage_percentage=$(coverage report --format=total)
            if [ $coverage_percentage -lt 80 ]; then
              echo "Coverage is less than 80%: $coverage_percentage%"
              exit 1
            else
              echo "Coverage is greater than 80, Success"
            fi
        