name: OnPullRequest

on:
  pull_request:

jobs:
  build-test-scan:
    runs-on: [ ubuntu-20.04 ]
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}
      PYTHONPATH: ${{ github.workspace }}/inteltrustauthorityclient:$PYTHONPATH
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      #- name: python linter TODO: Check if innersource provides aby linter.
       # uses: psf/black@stable

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'
          
      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Install dependencies via Poetry
        run:  poetry install

      - name: Run UT with Coverage enabled
        run: cd test && poetry run coverage run -m unittest discover -p 'test_*.py'

      - name: Check coverage percentage
        run: |
            cd test
            coverage_percentage=$(poetry run coverage report --format=total)
            if [ $coverage_percentage -lt 80 ]; then
              echo "Coverage is less than 80 %: $coverage_percentage %"
              exit 1
            else
              echo "Coverage is greater than 80 : $coverage_percentage %"
            fi
        
