name: "Security Scans"
on:
  workflow_dispatch:

permissions: read-all
  
jobs:
    bandit-scan:
        runs-on: [ self-hosted, taas ]
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
              with:
                fetch-depth: 0

            - name: Bandit Scan
              uses: intel-innersource/frameworks.devops.github.actions.bandit@main
              with:
                scan_path: .
                report_path: artifacts/ITAPythonClient
                exclude: .github

    Checkmarx:
        runs-on: [ self-hosted, taas ]
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
            - name: Scan
              uses: intel-innersource/frameworks.devops.github.actions.checkmarx@main
              with:
                    username: ${{ secrets.CHECKMARX_USERNAME }}
                    password: ${{ secrets.CHECKMARX_PASSWORD }}
                    http_proxy: ${{ secrets.HTTP_PROXY }}
                    https_proxy: ${{ secrets.HTTPS_PROXY }}
                    no_proxy: ${{ secrets.NO_PROXY }}
                    project: ITA Python Client
                    team: /CxServer/SP/Intel/IntelProjects/IAP/36221
